-- generated by {{&pkg.name}} {{&pkg.version}}

SET NOCOUNT ON

IF NOT EXISTS (
SELECT  schema_name
FROM    information_schema.schemata
WHERE   schema_name = '{{&options.schema}}' ) 

BEGIN
EXEC ( N'CREATE SCHEMA {{&options.schema}}' )
END

IF NOT EXISTS (
SELECT * 
FROM   INFORMATION_SCHEMA.TABLES 
WHERE  TABLE_SCHEMA = '{{&options.schema}}'
AND    TABLE_NAME   = '{{&options.table}}' )

BEGIN
EXEC ( N'
CREATE TABLE [{{&options.schema}}].[{{&options.table}}](
    name VARCHAR(100) PRIMARY KEY,
    created TIMESTAMP NOT NULL,
    checksum CHAR(40) NULL
)' )
END



{{#patches}}

-- {{&name}} - {{&file}}

IF EXISTS (SELECT 1 FROM "{{&options.schema}}"."{{&options.table}}" WHERE name = '{{&name}}')
BEGIN
	PRINT 'skip {{&name}}';
END
ELSE
BEGIN
    {{#dependencies}}
    IF NOT EXISTS (SELECT 1 FROM "{{&options.schema}}"."{{&options.table}}" WHERE name = '{{&name}}' AND (checksum = '{{&checksum}}' OR checksum IS NULL))
    BEGIN
        RAISERROR ('missing dependency or invalid checksum: {{&name}}', 10, 1)
        RETURN
    END
    {{/dependencies}}

    PRINT 'do {{&name}}';

    {{#parts}}
    EXEC (N'
{{{part}}}
    ')
    {{/parts}}

    INSERT INTO "{{&options.schema}}"."{{&options.table}}" (name, checksum) VALUES('{{&name}}', '{{&checksum}}');

    PRINT 'done {{&name}}';

END


{{/patches}}
